# -*- coding: utf-8 -*-
"""chatLucas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18q0SK94kcTWUBMHXgJnlJnz-z4-b1CJN
"""

from google.colab import drive
drive.mount('/content/drive')

import os, json, random
from IPython.display import display,HTML

caminho_json = '/content/drive/MyDrive/ChatBotKenji/banco.json'

if not os.path.exists(caminho_json):
  with open(caminho_json, 'w') as f:
    json.dump({}, f)

def carregar_banco():
  try:
    with open(caminho_json, 'r') as f:
      return json.load(f)
  except (json.JSONDecodeError, FileNotFoundError):
      return {}

def salva_banco(banco):
  with open(caminho_json,'w') as f:
    json.dump(banco, f ,indent=2)

def mostra_mensagem(origem, texto):
  cor ='#6495ED' if origem == 'bot' else '#98FB98'
  nome = 'Infinity' if origem == 'bot' else 'Lucas'
  display(HTML(f"<div style='color:{cor}; margin-bottom: 6px'><b>{nome}:</b>{texto}</div>"))

def ChatBotKenji():
  nome = "Infinity"
  mostra_mensagem("bot", f"olá! meu nome é{nome},sou um assistente virtual. Como posso ajudar?")
  mostra_mensagem("bot","digite<b>!ajuda!</b> para ver os comandos disponíveis.")

  banco = carregar_banco()

  while True:
    entrada = input("você: ").strip()
    mostra_mensagem("cliente", entrada)

    if entrada.lower() == "tchau":
        mostra_mensagem("bot",random.choice(["até a proxima!","estaremos esperando"]))
        break

    elif entrada.startswith("!ajuda"):
          comandos = """
          <ul>
            <li><b>!treinar</b>: ensinar nova pergunta e resposta</li>
            <li><b>!ver</b>: ver perguntas conhecidas</li>
            <li><b>!remover</b>: remover uma pergunta</li>
            <li><b>!limpar</b>: limpar todo o banco</li>
            <li><b>tchau</b>: encerrar conversa</li>
          </ul>
          """
          mostra_mensagem("bot", f"Aqui estão os comandos disponíveis:{comandos}")

    elif entrada.startswith("!treinar"):
        pergunta = input("Digite a nova pergunta: ").strip()
        resposta = input("Digite a resposta: ").strip()

        if pergunta in banco and resposta in banco[pergunta]:
            mostra_mensagem("bot", "Essa resposta já está cadastrada! 🙃")
        else:
            banco.setdefault(pergunta, []).append(resposta)
            salva_banco(banco)
            mostra_mensagem("bot", "Aprendido com sucesso! 🙌")

    elif entrada.startswith("!ver"):
        if banco:
            perguntas = "<br>".join(banco.keys())
            mostra_mensagem("bot", f"Perguntas conhecidas:<br>{perguntas}")
        else:
            mostra_mensagem("bot", "Ainda não aprendi nada 😓")

    elif entrada.startswith("!remover"):
        pergunta = input("Qual pergunta deseja remover? ").strip()
        if pergunta in banco:
            del banco[pergunta]
            salva_banco(banco)
            mostra_mensagem("bot", "Pergunta removida! ❌")
        else:
            mostra_mensagem("bot", "Essa pergunta não existe no banco.")

    elif entrada.startswith("!limpar"):
        confirma = input("Tem certeza? Digite 'sim' para confirmar: ").strip().lower()
        if confirma == "sim":
            banco.clear()
            salva_banco(banco)
            mostra_mensagem("bot", "Banco de dados limpo 🧹")
        else:
            mostra_mensagem("bot", "Ação cancelada.")

    elif entrada in banco:
        respostas = banco[entrada]
        mostra_mensagem("bot", random.choice(respostas))
    else:
        mostra_mensagem("bot", "Não sei responder isso 😓")
        nova = input("Como devo responder?\n").strip()
        if nova:
            banco.setdefault(entrada, []).append(nova)
            salva_banco(banco)
            mostra_mensagem("bot", "Aprendido! Obrigada 🙌")

ChatBotKenji()